---
- name: Run on db server
  hosts: localhost
  tasks:
  - name: build an image
    docker_image:
      name: suchismita1/spring-project
      path: target/*.war
      state: present

  - name: run container
    docker_container:
      name: webapps
      image: suchismita1/spring-project:latest
      state: started
      ports:
      - "8090:8080"
      tty: true
      detach: true

