---
- name: Run on localhost
  hosts: localhost
  tasks:
  - name: pull an image
    docker_image:
      name: suchismita1/spring-project:0.0.1
      source: pull

  - name: web container
    docker_container:
      name: webapp
      image: suchismita1/spring-project:0.0.1
      state: present
      ports:
      - "8085:8080"
      tty: true
      detach: true
