---
- name: Run on dbserver
  hosts: dbserver
  tasks:
  - name: pull an image
    docker_image:
      name: suchismita1/spring-project:0.0.1
      source: pull

  - name: run container
    docker_container:
      name: webapps
      image: suchismita1/spring-project:0.0.1
      state: started
      ports:
      - "8090:8080"
      tty: true
      detach: true
