---
- name: Run on localhost
  hosts: localhost
  tasks:
  - name: Copy Dockerfile
    copy: src=Dockerfile dest=/tmp/path/
  - name: Build spring image
    docker_image:
      path: /tmp/path/
      name: suchismita1/spring-project
      state: present

  - name: run container
    docker_container:
      name: webapps
      image: suchismita1/spring-project
      state: started
      ports:
      - "8085:8080"
      tty: true
      detach: true
